port: 3000
address: 0.0.0.0
metrics:
  prefix: dynode

jwt:
  secret: ""

webhook:
  enabled: false
  url: ""
  timeout: 2s

monitoring:
  enabled: false
  poll_interval: 10m
  max_sync_delay: 24s
  max_sync_blocks: 20
  latency_threshold: 250ms
  latency_threshold_percent: 20

request:
  timeout: 3s

headers:
  forward:
    - accept
    - content-type
    - content-encoding
    - content-length
    - te
  domains:
    public-eth.nownodes.io:
      - user-agent

retry:
  enabled: true
  max_attempts: 3
  errors:
    status_codes: [403, 429, 502, 503, 504]
    error_messages:
      - "daily request limit"
      - "rate limit"
      - "Exceeded the quota usage"
      - "Unauthorized"

cache:
  max_memory_mb: 1024

chain_types:
  ethereum:
    allowlist:
      - rpc_method: eth_chainId
      - rpc_method: eth_sendRawTransaction
    cache:
      - rpc_method: eth_chainId
        ttl: 1h
  bitcoin:
    allowlist:
      - path: /api/v2/address/**
        method: GET
      - path: /api/v2/sendtx/
        method: POST
  tron:
    cache:
      - path: /wallet/getchainparameters
        method: GET
        ttl: 1d
      - path: /wallet/listwitnesses
        method: GET
        ttl: 1d
      - path: /wallet/getaccount
        method: POST
        inflight: true
      - path: /wallet/getaccountresource
        method: POST
        inflight: true
      - path: /wallet/getReward
        method: POST
        inflight: true
  solana:
    cache:
      - rpc_method: getVoteAccounts
        ttl: 1h
  cosmos:
    cache:
      - path: /cosmos/staking/v1beta1/validators
        method: GET
        ttl: 1d
  hypercore:
    cache:
      - path: /info
        method: POST
        ttl: 1h
        params:
          type: metaAndAssetCtxs
  aptos:
    cache:
      - path: /v1/view
        method: POST
        ttl: 1h
        params:
          function: "0x1::delegation_pool::operator_commission_percentage"
