version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/core"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 7
      semver-patch-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
