/**
 * Generated by typeshare 1.12.0
 */

package com.gemwallet.android.model

import com.wallet.core.primitives.AddressName
import com.wallet.core.primitives.Asset
import com.wallet.core.primitives.Price
import com.wallet.core.primitives.Transaction
import kotlinx.serialization.Serializable

@Serializable
data class TransactionExtended (
    val transaction: Transaction,
    val asset: Asset,
    val feeAsset: Asset,
    val price: Price? = null,
    val feePrice: Price? = null,
    val assets: List<Asset>,
    val fromAddress: AddressName? = null,
    val toAddress: AddressName? = null,
)

